# Generated by Django 3.2.4 on 2021-08-08 12:20

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210808_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=app.models.MoneyField(default=0.0),
        ),
    ]
