# Generated by Django 3.2.4 on 2021-08-17 09:03

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_cart',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__id': builtins.id}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_active_cart', to='app.cart'),
        ),
    ]
